// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using UserService.DataAccess.Context;

#nullable disable

namespace UserService.DataAccess.Migrations
{
    [DbContext(typeof(UserServiceDbContext))]
    partial class UserServiceDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.17")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("UserService.DataAccess.Entitites.CvProject", b =>
                {
                    b.Property<Guid>("CvId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid");

                    b.HasKey("CvId", "ProjectId");

                    b.HasIndex("ProjectId");

                    b.ToTable("CvProjects");
                });

            modelBuilder.Entity("UserService.DataAccess.Entitites.PositionTechnology", b =>
                {
                    b.Property<Guid>("PositionId")
                        .HasColumnType("uuid");

                    b.Property<string>("TechnologyId")
                        .HasColumnType("character varying(100)");

                    b.HasKey("PositionId", "TechnologyId");

                    b.HasIndex("TechnologyId");

                    b.ToTable("PositionTechnologies", (string)null);
                });

            modelBuilder.Entity("UserService.DataAccess.Entitites.ProjectTechnology", b =>
                {
                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid");

                    b.Property<string>("TechnologyId")
                        .HasColumnType("character varying(100)");

                    b.HasKey("ProjectId", "TechnologyId");

                    b.HasIndex("TechnologyId");

                    b.ToTable("ProjectTechnologies", (string)null);
                });

            modelBuilder.Entity("UserService.Domain.Models.AccessRule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AttributeValueId")
                        .HasColumnType("uuid");

                    b.Property<int>("FilterOperator")
                        .HasColumnType("integer");

                    b.Property<Guid>("PositionId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("AttributeValueId");

                    b.HasIndex("PositionId");

                    b.ToTable("AccessRule", (string)null);
                });

            modelBuilder.Entity("UserService.Domain.Models.Attributes.AttributeCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasAlternateKey("Name");

                    b.ToTable("AttributeCategories", (string)null);
                });

            modelBuilder.Entity("UserService.Domain.Models.Attributes.AttributeDefinition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AttributeCategoryId")
                        .HasColumnType("uuid");

                    b.Property<int>("DataType")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("AttributeCategoryId");

                    b.ToTable("AttributeDefinitions", (string)null);

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("UserService.Domain.Models.Attributes.AttributeValue", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AttributeDefinitionId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("AttributeDefinitionId");

                    b.ToTable("AttributeValues", (string)null);

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("UserService.Domain.Models.Attributes.OneOfManyOption", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("OneOfManyId")
                        .HasColumnType("uuid");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("OneOfManyId");

                    b.HasIndex("Value", "OneOfManyId")
                        .IsUnique();

                    b.ToTable("OneOfManyOptions", (string)null);
                });

            modelBuilder.Entity("UserService.Domain.Models.Cv", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<long>("Likes")
                        .HasColumnType("bigint");

                    b.Property<Guid>("PositionId")
                        .HasColumnType("uuid");

                    b.Property<bool>("Published")
                        .HasColumnType("boolean");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasAlternateKey("UserId", "PositionId");

                    b.HasIndex("PositionId");

                    b.ToTable("Cvs", (string)null);
                });

            modelBuilder.Entity("UserService.Domain.Models.Discussion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("PositionId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("PositionId")
                        .IsUnique();

                    b.ToTable("Discussions", (string)null);
                });

            modelBuilder.Entity("UserService.Domain.Models.DiscussionMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("DiscussionId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("SentAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("DiscussionId");

                    b.HasIndex("UserId");

                    b.ToTable("DiscussionMessages", (string)null);
                });

            modelBuilder.Entity("UserService.Domain.Models.Position", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("ExpertiseLevel")
                        .HasColumnType("integer");

                    b.Property<long>("MaxProjects")
                        .HasColumnType("bigint");

                    b.Property<bool>("Restricted")
                        .HasColumnType("boolean");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("Positions", (string)null);
                });

            modelBuilder.Entity("UserService.Domain.Models.Project", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Projects", (string)null);
                });

            modelBuilder.Entity("UserService.Domain.Models.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("Roles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("06af8b49-9a2a-4017-af1d-c2d0ef25ec45"),
                            Name = "Regular"
                        },
                        new
                        {
                            Id = new Guid("d032d2d0-0681-442f-b784-b2a15c1a4dde"),
                            Name = "Recruiter"
                        },
                        new
                        {
                            Id = new Guid("7cfd6b8e-4289-4f97-911d-b24bb5608f68"),
                            Name = "Admin"
                        });
                });

            modelBuilder.Entity("UserService.Domain.Models.Technology", b =>
                {
                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Name");

                    b.ToTable("Technologies", (string)null);
                });

            modelBuilder.Entity("UserService.Domain.Models.Tokens.AccountConfirmationToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(36)
                        .HasColumnType("uuid");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasMaxLength(36)
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AccountConfirmationTokens");
                });

            modelBuilder.Entity("UserService.Domain.Models.Tokens.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(36)
                        .HasColumnType("uuid");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasMaxLength(36)
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("UserService.Domain.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsBlocked")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<Guid?>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValue(new Guid("06af8b49-9a2a-4017-af1d-c2d0ef25ec45"));

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("RoleId");

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("UserService.Domain.Models.UserAttributeValue", b =>
                {
                    b.Property<Guid>("AttributeValueId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("AttributeValueId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("UserAttributeValues", (string)null);
                });

            modelBuilder.Entity("UserService.Domain.Models.UserLikedCvs", b =>
                {
                    b.Property<Guid>("CvId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("CvId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("UserLikedCvs", (string)null);
                });

            modelBuilder.Entity("UserService.Domain.Models.Attributes.AttributeDefinitionOfOneOfMany", b =>
                {
                    b.HasBaseType("UserService.Domain.Models.Attributes.AttributeDefinition");

                    b.ToTable("AttributeDefinitionsOfOneOfMany");
                });

            modelBuilder.Entity("UserService.Domain.Models.Attributes.BooleanAttributeValue", b =>
                {
                    b.HasBaseType("UserService.Domain.Models.Attributes.AttributeValue");

                    b.Property<bool>("Value")
                        .HasColumnType("boolean");

                    b.ToTable("BooleanAttributeValues");
                });

            modelBuilder.Entity("UserService.Domain.Models.Attributes.DateAttributeValue", b =>
                {
                    b.HasBaseType("UserService.Domain.Models.Attributes.AttributeValue");

                    b.Property<DateOnly>("Value")
                        .HasColumnType("date");

                    b.ToTable("DateAttributeValues");
                });

            modelBuilder.Entity("UserService.Domain.Models.Attributes.ImageAttributeValue", b =>
                {
                    b.HasBaseType("UserService.Domain.Models.Attributes.AttributeValue");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.ToTable("ImageAttributeValues");
                });

            modelBuilder.Entity("UserService.Domain.Models.Attributes.MarkdownAttributeValue", b =>
                {
                    b.HasBaseType("UserService.Domain.Models.Attributes.AttributeValue");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("text");

                    b.ToTable("MarkdownAttributeValues");
                });

            modelBuilder.Entity("UserService.Domain.Models.Attributes.NumericAttributeValue", b =>
                {
                    b.HasBaseType("UserService.Domain.Models.Attributes.AttributeValue");

                    b.Property<float>("Value")
                        .HasColumnType("real");

                    b.ToTable("NumericAttributeValues");
                });

            modelBuilder.Entity("UserService.Domain.Models.Attributes.OneOfManyAttributeValue", b =>
                {
                    b.HasBaseType("UserService.Domain.Models.Attributes.AttributeValue");

                    b.Property<Guid>("OptionId")
                        .HasColumnType("uuid");

                    b.HasIndex("OptionId");

                    b.ToTable("OneOfManyAttributeValues");
                });

            modelBuilder.Entity("UserService.Domain.Models.Attributes.PeriodAttributeValue", b =>
                {
                    b.HasBaseType("UserService.Domain.Models.Attributes.AttributeValue");

                    b.Property<DateOnly>("EndValue")
                        .HasColumnType("date");

                    b.Property<DateOnly>("StartValue")
                        .HasColumnType("date");

                    b.ToTable("PeriodAttributeValues");
                });

            modelBuilder.Entity("UserService.Domain.Models.Attributes.StringAttributeValue", b =>
                {
                    b.HasBaseType("UserService.Domain.Models.Attributes.AttributeValue");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("text");

                    b.ToTable("StringAttributeValues");
                });

            modelBuilder.Entity("UserService.DataAccess.Entitites.CvProject", b =>
                {
                    b.HasOne("UserService.Domain.Models.Cv", "Cv")
                        .WithMany()
                        .HasForeignKey("CvId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UserService.Domain.Models.Project", "Project")
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cv");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("UserService.DataAccess.Entitites.PositionTechnology", b =>
                {
                    b.HasOne("UserService.Domain.Models.Position", "Position")
                        .WithMany()
                        .HasForeignKey("PositionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UserService.Domain.Models.Technology", "Technology")
                        .WithMany()
                        .HasForeignKey("TechnologyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Position");

                    b.Navigation("Technology");
                });

            modelBuilder.Entity("UserService.DataAccess.Entitites.ProjectTechnology", b =>
                {
                    b.HasOne("UserService.Domain.Models.Project", "Project")
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UserService.Domain.Models.Technology", "Technology")
                        .WithMany()
                        .HasForeignKey("TechnologyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");

                    b.Navigation("Technology");
                });

            modelBuilder.Entity("UserService.Domain.Models.AccessRule", b =>
                {
                    b.HasOne("UserService.Domain.Models.Attributes.AttributeValue", "AttributeValue")
                        .WithMany()
                        .HasForeignKey("AttributeValueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UserService.Domain.Models.Position", null)
                        .WithMany("AccessRules")
                        .HasForeignKey("PositionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AttributeValue");
                });

            modelBuilder.Entity("UserService.Domain.Models.Attributes.AttributeDefinition", b =>
                {
                    b.HasOne("UserService.Domain.Models.Attributes.AttributeCategory", "AttributeCategory")
                        .WithMany()
                        .HasForeignKey("AttributeCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AttributeCategory");
                });

            modelBuilder.Entity("UserService.Domain.Models.Attributes.AttributeValue", b =>
                {
                    b.HasOne("UserService.Domain.Models.Attributes.AttributeDefinition", "AttributeDefinition")
                        .WithMany()
                        .HasForeignKey("AttributeDefinitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AttributeDefinition");
                });

            modelBuilder.Entity("UserService.Domain.Models.Attributes.OneOfManyOption", b =>
                {
                    b.HasOne("UserService.Domain.Models.Attributes.AttributeDefinitionOfOneOfMany", null)
                        .WithMany("OneOfManyOptions")
                        .HasForeignKey("OneOfManyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("UserService.Domain.Models.Cv", b =>
                {
                    b.HasOne("UserService.Domain.Models.Position", "Position")
                        .WithMany()
                        .HasForeignKey("PositionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UserService.Domain.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Position");

                    b.Navigation("User");
                });

            modelBuilder.Entity("UserService.Domain.Models.Discussion", b =>
                {
                    b.HasOne("UserService.Domain.Models.Position", "Position")
                        .WithOne()
                        .HasForeignKey("UserService.Domain.Models.Discussion", "PositionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Position");
                });

            modelBuilder.Entity("UserService.Domain.Models.DiscussionMessage", b =>
                {
                    b.HasOne("UserService.Domain.Models.Discussion", null)
                        .WithMany("Messages")
                        .HasForeignKey("DiscussionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UserService.Domain.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("User");
                });

            modelBuilder.Entity("UserService.Domain.Models.Project", b =>
                {
                    b.HasOne("UserService.Domain.Models.User", null)
                        .WithMany("Projects")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("UserService.Domain.Models.Tokens.AccountConfirmationToken", b =>
                {
                    b.HasOne("UserService.Domain.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("UserService.Domain.Models.Tokens.RefreshToken", b =>
                {
                    b.HasOne("UserService.Domain.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("UserService.Domain.Models.User", b =>
                {
                    b.HasOne("UserService.Domain.Models.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.OwnsOne("UserService.Domain.Models.ProfileData", "ProfileData", b1 =>
                        {
                            b1.Property<Guid>("UserId")
                                .HasColumnType("uuid");

                            b1.Property<string>("FirstName")
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)");

                            b1.Property<string>("LastName")
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)");

                            b1.Property<string>("Location")
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)");

                            b1.Property<string>("PersonalPhoto")
                                .HasColumnType("text");

                            b1.HasKey("UserId");

                            b1.ToTable("Users");

                            b1.WithOwner()
                                .HasForeignKey("UserId");
                        });

                    b.Navigation("ProfileData")
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("UserService.Domain.Models.UserAttributeValue", b =>
                {
                    b.HasOne("UserService.Domain.Models.Attributes.AttributeValue", "AttributeValue")
                        .WithMany()
                        .HasForeignKey("AttributeValueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UserService.Domain.Models.User", "User")
                        .WithMany("Attributes")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AttributeValue");

                    b.Navigation("User");
                });

            modelBuilder.Entity("UserService.Domain.Models.UserLikedCvs", b =>
                {
                    b.HasOne("UserService.Domain.Models.Cv", "Cv")
                        .WithMany()
                        .HasForeignKey("CvId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UserService.Domain.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cv");

                    b.Navigation("User");
                });

            modelBuilder.Entity("UserService.Domain.Models.Attributes.AttributeDefinitionOfOneOfMany", b =>
                {
                    b.HasOne("UserService.Domain.Models.Attributes.AttributeDefinition", null)
                        .WithOne()
                        .HasForeignKey("UserService.Domain.Models.Attributes.AttributeDefinitionOfOneOfMany", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("UserService.Domain.Models.Attributes.BooleanAttributeValue", b =>
                {
                    b.HasOne("UserService.Domain.Models.Attributes.AttributeValue", null)
                        .WithOne()
                        .HasForeignKey("UserService.Domain.Models.Attributes.BooleanAttributeValue", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("UserService.Domain.Models.Attributes.DateAttributeValue", b =>
                {
                    b.HasOne("UserService.Domain.Models.Attributes.AttributeValue", null)
                        .WithOne()
                        .HasForeignKey("UserService.Domain.Models.Attributes.DateAttributeValue", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("UserService.Domain.Models.Attributes.ImageAttributeValue", b =>
                {
                    b.HasOne("UserService.Domain.Models.Attributes.AttributeValue", null)
                        .WithOne()
                        .HasForeignKey("UserService.Domain.Models.Attributes.ImageAttributeValue", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("UserService.Domain.Models.Attributes.MarkdownAttributeValue", b =>
                {
                    b.HasOne("UserService.Domain.Models.Attributes.AttributeValue", null)
                        .WithOne()
                        .HasForeignKey("UserService.Domain.Models.Attributes.MarkdownAttributeValue", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("UserService.Domain.Models.Attributes.NumericAttributeValue", b =>
                {
                    b.HasOne("UserService.Domain.Models.Attributes.AttributeValue", null)
                        .WithOne()
                        .HasForeignKey("UserService.Domain.Models.Attributes.NumericAttributeValue", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("UserService.Domain.Models.Attributes.OneOfManyAttributeValue", b =>
                {
                    b.HasOne("UserService.Domain.Models.Attributes.AttributeValue", null)
                        .WithOne()
                        .HasForeignKey("UserService.Domain.Models.Attributes.OneOfManyAttributeValue", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UserService.Domain.Models.Attributes.OneOfManyOption", "Option")
                        .WithMany()
                        .HasForeignKey("OptionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Option");
                });

            modelBuilder.Entity("UserService.Domain.Models.Attributes.PeriodAttributeValue", b =>
                {
                    b.HasOne("UserService.Domain.Models.Attributes.AttributeValue", null)
                        .WithOne()
                        .HasForeignKey("UserService.Domain.Models.Attributes.PeriodAttributeValue", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("UserService.Domain.Models.Attributes.StringAttributeValue", b =>
                {
                    b.HasOne("UserService.Domain.Models.Attributes.AttributeValue", null)
                        .WithOne()
                        .HasForeignKey("UserService.Domain.Models.Attributes.StringAttributeValue", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("UserService.Domain.Models.Discussion", b =>
                {
                    b.Navigation("Messages");
                });

            modelBuilder.Entity("UserService.Domain.Models.Position", b =>
                {
                    b.Navigation("AccessRules");
                });

            modelBuilder.Entity("UserService.Domain.Models.User", b =>
                {
                    b.Navigation("Attributes");

                    b.Navigation("Projects");
                });

            modelBuilder.Entity("UserService.Domain.Models.Attributes.AttributeDefinitionOfOneOfMany", b =>
                {
                    b.Navigation("OneOfManyOptions");
                });
#pragma warning restore 612, 618
        }
    }
}
